#!/bin/bash
#SBATCH --account=def-panos
#SBATCH --gres=gpu:1 
#SBATCH --cpus-per-task=2
#SBATCH --mem-per-cpu=8G
#SBATCH --time=00:50:00
#SBATCH --mail-user=sizhuoqi@gmail.com
#SBATCH --mail-type=ALL

module load python/3.6
module load nixpkgs/16.09  intel/2018.3  cuda/10.1 cudnn/7.6.5

# Prepare virtualenv
virtualenv --no-download $SLURM_TMPDIR/env
source $SLURM_TMPDIR/env/bin/activate
pip install --no-index setuptools==41.6.0 tensorflow_gpu==2.2.0 opencv_python_headless==4.1.1.26 numpy
#pip install --no-index tensorflow_gpu==2.2.0 opencv_python_headless==4.1.1.26 numpy

export LD_LIBRARY_PATH={$LD_LIBRARY_PATH}:$CUDA_HOME/lib64:/cvmfs/soft.computecanada.ca/easybuild/software/2017/CUDA/cuda10.1/cudnn/7.6.5/lib64/

cd /home/sizhuoqi/projects/def-panos/sizhuoqi/ITMO_with_fast_SRGAN
echo $PWD
echo "Inference..."
python infer_itmo.py\
--image_dir images  "/home/sizhuoqi/projects/def-panos/sizhuoqi/ITMO_with_fast_SRGAN/images"\
--output_dir output "/home/sizhuoqi/projects/def-panos/sizhuoqi/ITMO_with_fast_SRGAN/output"\
--gen "models/20200616091300_28500_generator.h5"